#job_name: 'prometheus'
#static_configs:
#  - targets: ['127.0.0.1:9090']

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'camel-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
